### ISSUE TITLE
AttributeError: 'Variant' object has no attribute 'gene'

### ISSUE THREAD

**Issue by WhalleyT** [theiagen/tbp-parser#15]
Hi, I have encountered this error both using the Docker container provided as well as a local installation. I created a tb-profiler report with default arguments from FASTQ with `tb-profiler profile --read1 R_1.fastq.gz --read2 R_2.fastq.gz`. I ran `python3 magma/tbp-parser/tbp_parser/tbp_parser.py results/tbprofiler.results.json bam/tbprofiler.bam` and the following error was reported:

```
Traceback (most recent call last):
  File "/home/ubuntu/magma/tbp-parser/tbp_parser/tbp_parser.py", line 76, in <module>
    main()
  File "/home/ubuntu/magma/tbp-parser/tbp_parser/tbp_parser.py", line 72, in main
    parse.run()
  File "/home/ubuntu/magma/tbp-parser/tbp_parser/Parser.py", line 108, in run
    laboratorian.create_laboratorian_report()
  File "/home/ubuntu/magma/tbp-parser/tbp_parser/Laboratorian.py", line 111, in create_laboratorian_report
    row_list = self.iterate_section(input_json["dr_variants"], row_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/magma/tbp-parser/tbp_parser/Laboratorian.py", line 36, in iterate_section
    globals.GENES_REPORTED.add(variant.gene)
                               ^^^^^^^^^^^^
AttributeError: 'Variant' object has no attribute 'gene'
```

Are there any parameters needed to be added in `tb-profiler`/modifications made to the BAM that aren't in the README?

**Comment by sage-wright** [comment]
Hi WhalleyT, 

Thanks for reaching out! Are your inputs produced using TBProfiler v6+? If so, please use the latest version of tbp-parser (v2.1.0) which will correct this issue, which was released today!

This is because TBProfiler v6 input JSONs use different language than earlier versions, and the v1 versions of tbp-parser are not compatible with the latest version of TBProfiler. The v2+ versions of tbp-parser are built for TBProfiler v6 and above, so this issue regarding the lack of "gene" attribute will no longer appear (TBProfiler v6 calls it "gene_name"). 

If this doesn't work, if you could send me your input files so I can replicate the issue, I'd appreciate that!

Thanks!

**Comment by WhalleyT** [comment]
Hi Sage,

No worries, I appreciate the response! 

Yes I had a little play around and noticed that was the issue:- prior to that I never noticed that the JSON had change (nor could spot it in tb-profiler's docs). I'll have a go today and report back if it works or not, fingers crossed 🙂 

Thanks, Tom
